services:
  sveltekit-web:
    build:
      context: .
      target: dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - luna-net

networks:
  luna-net:
    driver: bridge
