services:
  sveltekit-web:
    build:
      context: .
      target: dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - LUNA_AUGUR_HOST=http://django-web:8000
    networks:
      - luna-net
      - augur-net

networks:
  luna-net:
    driver: bridge
  augur-net:
    external: true

